// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCs4sNBvf1VWlBVrAr5IwYr-EFrum-eRIE',
    appId: '1:53350523190:web:ecf02091472222144fd397',
    messagingSenderId: '53350523190',
    projectId: 'finechecker-197b1',
    authDomain: 'finechecker-197b1.firebaseapp.com',
    storageBucket: 'finechecker-197b1.firebasestorage.app',
    measurementId: 'G-HM539TW7K4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQdd1CYUjTqdrFbrRaDHTOI8lKPP5ngV8',
    appId: '1:53350523190:android:e671744937c0878a4fd397',
    messagingSenderId: '53350523190',
    projectId: 'finechecker-197b1',
    storageBucket: 'finechecker-197b1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9fXwB0m8HlIvPnpTcKYi469RIkmQsS8Y',
    appId: '1:53350523190:ios:80671b170f0b25594fd397',
    messagingSenderId: '53350523190',
    projectId: 'finechecker-197b1',
    storageBucket: 'finechecker-197b1.firebasestorage.app',
    iosBundleId: 'com.example.fineChecker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9fXwB0m8HlIvPnpTcKYi469RIkmQsS8Y',
    appId: '1:53350523190:ios:80671b170f0b25594fd397',
    messagingSenderId: '53350523190',
    projectId: 'finechecker-197b1',
    storageBucket: 'finechecker-197b1.firebasestorage.app',
    iosBundleId: 'com.example.fineChecker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCs4sNBvf1VWlBVrAr5IwYr-EFrum-eRIE',
    appId: '1:53350523190:web:b55783fc7a957a854fd397',
    messagingSenderId: '53350523190',
    projectId: 'finechecker-197b1',
    authDomain: 'finechecker-197b1.firebaseapp.com',
    storageBucket: 'finechecker-197b1.firebasestorage.app',
    measurementId: 'G-C45HY2Z9BQ',
  );
}
